/* eslint-disable no-useless-escape */
import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  // English placeholder: Your 't' function references 'translations.en',
  // so this object must exist to prevent runtime errors.
  en: {
    brand: "SwapX",
    tagline: "Swap anything for anything",
    heroTitle: "The Future of Trading",
    heroSubtitle: "Swap cars for tech, art for real estate...",
    explore: "Explore Trades",
    listItem: "List Item",
    categories: "Categories",
    myItems: "My Items",
    messages: "Messages",
    profile: "Profile",
    search: "Search items...",
    viewAll: 'View All',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    browseItems: 'Browse Items',
    signIn: 'Sign In',
    register: 'Register',
    editProfile: 'Edit Profile',
    cars: 'Cars',
    motorcycles: 'Motorcycles',
    boats: 'Boats',
    realEstate: 'Real Estate',
    phones: 'Phones',
    computers: 'Computers',
    gaming: 'Gaming',
    cameras: 'Cameras',
    watches: 'Watches',
    jewelry: 'Jewelry',
    handbags: 'Handbags',
    sneakers: 'Sneakers',
    fashion: 'Fashion',
    furniture: 'Furniture',
    art: 'Art',
    pets: 'Pets',
    services: 'Services',
    other: 'Other',
    condition: 'Condition',
    location: 'Location',
    lookingFor: 'Looking For',
    cashFlexibility: 'Cash Flexibility',
    estimated: 'Estimated',
    makeOffer: 'Make Offer',
    yourOffer: 'Your Offer',
    theirItem: 'Their Item',
    addCash: 'Add Cash',
    requestCash: 'Request Cash',
    sendOffer: 'Send Offer',
    balance: 'Balance',
    tradeOfferDescription: 'Select an item to offer, or create a new one, and/or add cash.',
    createNewItemOffer: 'Create New Item Offer',
    image: 'Image',
    title: 'Title',
    description: 'Description',
    estimatedValue: 'Estimated Value',
    new: 'New',
    likeNew: 'Like New',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    willingToAdd: 'Willing to add cash',
    willingToReceive: 'Willing to receive cash',
    both: 'Both',
    tradeOnly: 'Trade Only',
    Anything: 'Anything',
    'Like_new': 'Like New',
    'willing_to_add': 'Willing to add cash',
    'willing_to_receive': 'Willing to receive cash',
    'trade_only': 'Trade Only',
    featuredItems: 'Featured Items',
    howItWorks: {
      title: 'How SwapX Works',
      step1: {
        title: '1. List Your Item',
        description: "Snap some pics, write a catchy description, and set an estimated value for your item. Make it shine!",
      },
      step2: {
        title: '2. Discover Treasures',
        description: 'Browse a world of items from other users. Use our search to find exactly what you\'re looking for. Your next find awaits.',
      },
      step3: {
        title: '3. Seal the Deal',
        description: 'Propose a swap by offering your items. You can add or request cash to balance the deal. Negotiate, agree, and get ready to swap!',
      },
    },
    active: 'Active',
    pending: 'Pending',
    requestCashFromThem: 'Request Cash From Them',
    message: 'Message',
    newOfferTitlePlaceholder: "Enter a concise title for your item (e.g., 'Vintage Watch', 'Gaming PC')",
    newOfferDescriptionPlaceholder: "Provide a detailed description of your item, including condition, features, and any flaws.",
    estimatedValueHelp: "Enter the estimated value of your item in USD. This helps balance the trade.",
    imageHelp: "Upload a clear image of your item. Max 1 file. (Accepted: JPG, PNG)",
    addCashHelp: "Use the slider to add cash to your offer. Max value will be based on the target item's estimated value.",
    requestCashHelp: "Use the slider to request cash from the other party. Max value will be based on the target item's estimated value.",
    sendMessagePlaceholder: "Write a friendly message to the other party, explaining your offer.",
    tradeOfferSentSuccessfully: "Trade offer sent successfully!",
    failedToSendOffer: "Failed to send trade offer.",
    preview: "Preview",
    lookingForHelp: "Select categories of items you are looking to receive in a trade. You can select multiple.",
    cashFlexibilityHelp: "Define your cash preferences. 'Willing to add cash' means you can offer cash. 'Willing to receive cash' means you can request cash. 'Both' allows either. 'Trade only' means no cash involved.",
    titleRequired: "Title is required.",
    categoryRequired: "Category is required.",
    valueRequired: "Estimated value is required.",
        minimumValue: "Minimum value is 1.",
        quickLinks: "Quick Links",
        company: "Company",
        aboutUs: "About Us",
        careers: "Careers",
        press: "Press",
        legal: "Legal",
        termsOfService: "Terms of Service",
            privacyPolicy: "Privacy Policy",
            myCoins: "My Coins",
            yourCoins: "Your Coins",
            dailyRewardInfo: "You receive 5 coins daily upon logging in.",
            nextReward: "Next reward can be claimed after:",
            coinUsage: "Coin Usage",
            featureItemWithCoins: "You can spend coins to feature your items. Featured items appear prominently and get more visibility.",
            featureCost: "Featuring an item costs 5 coins and lasts for 12 hours. You can feature your items from the 'My Items' page.",
            availableNow: "Available Now",
          },
          he: {
            brand: "SwapX",
            tagline: "החלף כל דבר בכל דבר",
            heroSubtitle: "החלף מכוניות בטכנולוגיה, אמנות בנדלן...",
            explore: "חקור עסקאות",
            listItem: "הוסף פריט",
            categories: "קטגוריות",
            myItems: "הפריטים שלי",
            messages: "הודעות",
            profile: "פרופיל",
            search: "חפש פריטים...",
            viewAll: 'הצג הכל',
            admin: 'מנהל',
            login: 'התחבר',
            logout: 'התנתק',
            browseItems: 'עיון בפריטים',
            signIn: 'התחבר',
            register: 'הירשם',
            editProfile: 'ערוך פרופיל',
            heroTitle: "העתיד של המסחר",
            cars: 'מכוניות',
            motorcycles: 'אופנועים',
            boats: 'סירות',
            realEstate: 'נדל"ן',
            phones: 'טלפונים',
            computers: 'מחשבים',
            gaming: 'גיימינג',
            cameras: 'מצלמות',
            watches: 'שעונים',
            jewelry: 'תכשיטים',
            handbags: 'תיקים',
            sneakers: 'נעלי ספורט',
            fashion: 'אופנה',
            furniture: 'ריהוט',
            art: 'אמנות',
            pets: 'חיות מחמד',
            services: 'שירותים',
            other: 'אחר',
            condition: 'מצב',
            location: 'מיקום',
            lookingFor: 'מחפש/ת',
            cashFlexibility: 'גמישות במזומן',
            estimated: 'שווי מוערך',
            makeOffer: 'הצע הצעה',
            yourOffer: 'ההצעה שלך',
            theirItem: 'הפריט שלהם',
            addCash: 'הוסף מזומן',
            requestCash: 'בקש מזומן',
            sendOffer: 'שלח הצעה',
            balance: 'איזון',
            tradeOfferDescription: 'בחר פריט להציע, או צור חדש, ו/או הוסף מזומן.',
            createNewItemOffer: 'צור הצעת פריט חדש',
            image: 'תמונה',
            title: 'כותרת',
            description: 'תיאור',
            estimatedValue: 'שווי מוערך',
            new: 'חדש',
            likeNew: 'כמו חדש',
            excellent: 'מצוין',
            good: 'טוב',
            fair: 'סביר',
            willingToAdd: 'מוכן להוסיף מזומן',
            willingToReceive: 'מוכן לקבל מזומן',
            both: 'שניהם',
            tradeOnly: 'החלפה בלבד',
            Anything: 'הכל',
            'Like_new': 'כמו חדש',
            'willing_to_add': 'מוכן להוסיף מזומן',
            'willing_to_receive': 'מוכן לקבל מזומן',
            'trade_only': 'החלפה בלבד',
            featuredItems: 'פריטים נבחרים',
            howItWorks: {
              title: 'איך סוואפ-אקס עובד',
              step1: {
                title: '1. הציגו את הפריט שלכם',
                description: "צלמו כמה תמונות, כתבו תיאור מושך וקבעו שווי מוערך לפריט שלכם. גרמו לו לבלוט!",
              },
              step2: {
                title: '2. גלו אוצרות',
                description: 'דפדפו בעולם של פריטים ממשתמשים אחרים. השתמשו בחיפוש שלנו כדי למצוא בדיוק את מה שאתם מחפשים. המציאה הבאה שלכם מחכה.',
              },
              step3: {
                title: '3. סגרו עסקה',
                description: 'הציעו החלפה על ידי הצעת הפריטים שלכם. תוכלו להוסיף או לבקש מזומן כדי לאזן את העסקה. נהלו משא ומתן, הסכימו והתכוננו להחלפה!',
              },
            },
            active: 'פעיל',
            pending: 'ממתין',
            requestCashFromThem: 'בקש מהם מזומן',
            message: 'הודעה',
            newOfferTitlePlaceholder: "הכנס כותרת תמציתית לפריט שלך (לדוגמה, 'שעון וינטג', 'מחשב גיימינג')",
            newOfferDescriptionPlaceholder: "ספק תיאור מפורט של הפריט שלך, כולל מצב, תכונות וכל פגמים.",
            estimatedValueHelp: "הכנס את השווי המוערך של הפריט שלך בדולר. זה עוזר לאזן את העסקה.",
            imageHelp: "העלה תמונה ברורה של הפריט שלך. קובץ אחד מקסימום. (פורמטים נתמכים: JPG, PNG)",
            addCashHelp: "השתמש בסליידר כדי להוסיף מזומן להצעה שלך. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
            requestCashHelp: "השתמש בסליידר כדי לבקש מזומן מהצד השני. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
            sendMessagePlaceholder: "כתוב הודעה ידידותית לצד השני, הסבר את הצעתך.",
            tradeOfferSentSuccessfully: "הצעת החלפה נשלחה בהצלחה!",
            failedToSendOffer: "שליחת הצעת החלפה נכשלה.",
            preview: "תצוגה מקדימה",
            lookingForHelp: "בחר קטגוריות של פריטים שאתה מחפש לקבל בהחלפה. באפשרותך לבחור מספר קטגוריות.",
            cashFlexibilityHelp: "הגדר את העדפות המזומן שלך. 'מוכן להוסיף מזומן' פירושו שאתה יכול להציע מזומן. 'מוכן לקבל מזומן' פירושו שאתה יכול לבקש מזומן. 'שניהם' מאפשר את שניהם. 'החלפה בלבד' פירושו ללא מזומן.",
            titleRequired: "נדרשת כותרת.",
            categoryRequired: "נדרשת קטגוריה.",
            valueRequired: "נדרש שווי מוערך.",
            minimumValue: "הערך המינימלי הוא 1.",
            quickLinks: "קישורים מהירים",
            company: "חברה",
            aboutUs: "אודותינו",
            careers: "קריירה",
            press: "עיתונות",
            legal: "משפטי",
            termsOfService: "תנאי שימוש",
            privacyPolicy: "מדיניות פרטיות",
            myCoins: "המטבעות שלי",
            yourCoins: "המטבעות שלך",
            dailyRewardInfo: "אתה מקבל 5 מטבעות יומי בכניסה.",
            nextReward: "ניתן לתבוע את התגמול הבא לאחר:",
            coinUsage: "שימוש במטבעות",
            featureItemWithCoins: "אתה יכול להשתמש במטבעות כדי להבליט את הפריטים שלך. פריטים מובלטים מופיעים באופן בולט ומקבלים יותר נראות.",
            featureCost: "הבלטת פריט עולה 5 מטבעות ונמשכת 12 שעות. אתה יכול להבליט את הפריטים שלך מדף 'הפריטים שלי'.",
            availableNow: "זמין כעת",
          },  ar: {
    brand: "SwapX",
    tagline: "بادل أي شيء بأي شيء",
    heroTitle: "مستقبل التداول",
    heroSubtitle: "استبدل السيارات بالتكنولوجيا، والفن بالعقارات...",
    explore: "استكشف الصفقات",
    listItem: "أضف سلعة",
    categories: "الفئات",
    myItems: "سلعي",
    messages: "الرسائل",
    profile: "الملف الشخصي",
    search: "ابحث عن سلع...",
    viewAll: 'عرض الكل',
    admin: 'مدير',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    cars: 'سيارات',
    motorcycles: 'دراجات نارية',
    boats: 'قوارب',
    realEstate: 'عقارات',
    phones: 'هواتف',
    computers: 'أجهزة كمبيوتر',
    gaming: 'ألعاب',
    cameras: 'كاميرات',
    watches: 'ساعات',
    jewelry: 'مجوهرات',
    handbags: 'حقائب يد',
    sneakers: 'أحذية رياضية',
    fashion: 'أزياء',
    furniture: 'أثاث',
    art: 'فن',
    pets: 'حيوانات أليفة',
    services: 'خدمات',
    other: 'أخرى',
    condition: 'الحالة',
    location: 'الموقع',
    lookingFor: 'يبحث عن',
    cashFlexibility: 'المرونة النقدية',
    estimated: 'القيمة المقدرة',
    makeOffer: 'قدم عرضًا',
    yourOffer: 'عرضك',
    theirItem: 'سلعتهم',
    addCash: 'أضف نقودًا',
    requestCash: 'اطلب نقودًا',
    sendOffer: 'أرسل العرض',
    balance: 'توازن',
    tradeOfferDescription: 'اختر سلعة لتقديمها، أو أنشئ سلعة جديدة، و/أو أضف نقودًا.',
    image: 'الصورة',
    title: 'العنوان',
    description: 'الوصف',
    estimatedValue: 'القيمة المقدرة',
    new: 'جديد',
    likeNew: 'شبه جديد',
    excellent: 'ممتاز',
    good: 'جيد',
    fair: 'مقبول',
    willingToAdd: 'على استعداد لإضافة نقود',
    willingToReceive: 'على استعداد لتلقي نقود',
    both: 'كلاهما',
    tradeOnly: 'مقايضة فقط',
    featuredItems: 'سلع مميزة',
    howItWorks: {
      title: 'كيف يعمل',
      step1: {
        title: '1. أضف سلعتك',
        description: 'التقط بعض الصور، واكتب وصفًا، وحدد قيمة تقديرية لما تريد مقايضته.',
      },
      step2: {
        title: '2. ابحث عن تطابق',
        description: 'تصفح السلع من الآخرين أو ابحث عن شيء محدد. انظر ماذا يبحث الآخرون في المقابل.',
      },
      step3: {
        title: '3. قم بالمبادلة',
        description: 'اقترح مبادلة عن طريق عرض سلعك، مع إمكانية إضافة مبلغ نقدي لموازنة الصفقة. تفاوض وأكمل المبادلة!',
      },
    },
    active: 'نشط',
    pending: 'قيد الانتظار',
    requestCashFromThem: 'اطلب نقودًا منهم',
    message: 'رسالة',
    newOfferTitlePlaceholder: "أدخل عنوانًا موجزًا لسلعتك (مثل 'ساعة عتيقة', 'جهاز كمبيوتر للألعاب')",
    newOfferDescriptionPlaceholder: "قدم وصفًا تفصيليًا لسلعتك، بما في ذلك الحالة والميزات وأي عيوب.",
    estimatedValueHelp: "أدخل القيمة المقدرة لسلعتك بالدولار الأمريكي. هذا يساعد على موازنة الصفقة.",
    imageHelp: "حمّل صورة واضحة لسلعتك. ملف واحد كحد أقصى. (الأنواع المقبولة: JPG, PNG)",
    addCashHelp: "استخدم شريط التمرير لإضافة النقود إلى عرضك. ستستند القيمة القصوى إلى القيمة المقدرة للسلعة المستهدفة.",
    requestCashHelp: "استخدم شريط التمرير لطلب النقود من الطرف الآخر. ستستند القيمة القصوى إلى القيمة المقدرة للسلعة المستهدفة.",
    sendMessagePlaceholder: "اكتب رسالة ودية للطرف الآخر، موضحًا عرضك.",
    tradeOfferSentSuccessfully: "تم إرسال عرض المبادلة بنجاح!",
    failedToSendOffer: "فشل إرسال عرض المبادلة.",
    preview: "معاينة",
    lookingForHelp: "اختر فئات السلع التي تتطلع لاستلامها في المبادلة. يمكنك اختيار عدة فئات.",
    cashFlexibilityHelp: "حدد تفضيلاتك النقدية. 'مستعد لإضافة نقود' يعني أنك تستطيع عرض النقود. 'مستعد لتلقي نقود' يعني أنك تستطيع طلب النقود. 'كلاهما' يسمح بأي منهما. 'مقايضة فقط' تعني عدم وجود نقود.",
    titleRequired: "العنوان مطلوب.",
    categoryRequired: "الفئة مطلوبة.",
    valueRequired: "القيمة المقدرة مطلوبة.",
    minimumValue: "الحد الأدنى للقيمة هو 1.",
  },
  ru: {
    brand: "SwapX",
    tagline: "Обменяй что угодно на что угодно",
    heroTitle: "Будущее Торговли",
    heroSubtitle: "Обменивайте машины на технику, искусство на недвижимость...",
    explore: "Исследуйте Сделки",
    listItem: "Выставить Предмет",
    categories: "Категории",
    myItems: "Мои Предметы",
    messages: "Сообщения",
    profile: "Профиль",
    search: "Искать предметы...",
    viewAll: 'Посмотреть все',
    admin: 'Админ',
    login: 'Войти',
    logout: 'Выйти',
    cars: 'Машины',
    motorcycles: 'Мотоциклы',
    boats: 'Лодки',
    realEstate: 'Недвижимость',
    phones: 'Телефоны',
    computers: 'Компьютеры',
    gaming: 'Игры',
    cameras: 'Камеры',
    watches: 'Часы',
    jewelry: 'Украшения',
    handbags: 'Сумки',
    sneakers: 'Кроссовки',
    fashion: 'Мода',
    furniture: 'Мебель',
    art: 'Искусство',
    pets: 'Животные',
    services: 'Услуги',
    other: 'Другое',
    condition: 'Состояние',
    location: 'Местоположение',
    lookingFor: 'Ищу',
    cashFlexibility: 'Гибкость в наличных',
    estimated: 'Оценочная стоимость',
    makeOffer: 'Сделать предложение',
    yourOffer: 'Ваше предложение',
    theirItem: 'Их предмет',
    addCash: 'Добавить наличные',
    requestCash: 'Запросить наличные',
    sendOffer: 'Отправить предложение',
    balance: 'Баланс',
    tradeOfferDescription: 'Выберите предмет для предложения или создайте новый и/или добавьте наличные.',
    createNewItemOffer: 'Создать новое предложение предмета',
    title: 'Название',
    description: 'Описание',
    estimatedValue: 'Оценочная стоимость',
    image: 'Изображение',
    new: 'Новое',
    likeNew: 'Как новое',
    excellent: 'Отличное',
    good: 'Хорошее',
    fair: 'Удовлетворительное',
    willingToAdd: 'Готов добавить наличные',
    willingToReceive: 'Готов получить наличные',
    both: 'И то, и другое',
    tradeOnly: 'Только обмен',
    featuredItems: 'Рекомендуемые товары',
    howItWorks: {
      title: 'Как это работает',
      step1: {
        title: '1. Выставите свой предмет',
        description: 'Сделайте несколько фотографий, напишите описание и установите оценочную стоимость того, что вы хотите обменять.',
      },
      step2: {
        title: '2. Найдите совпадение',
        description: 'Просматривайте предметы других пользователей или ищите что-то конкретное. Смотрите, что другие ищут взамен.',
      },
      step3: {
        title: '3. Совершите обмен',
        description: 'Предложите обмен, предложив свои предметы, с возможностью добавления наличных для уравновешивания сделки. Договаривайтесь и завершайте обмен!',
      },
    },
    active: 'Активные',
    pending: 'В ожидании',
    traded: 'Обменяно',
    requestCashFromThem: 'Запросить наличные у них',
    message: 'Сообщение',
    newOfferTitlePlaceholder: "Введите краткое название для вашего предмета (например, 'Винтажные часы', 'Игровой ПК')",
    newOfferDescriptionPlaceholder: "Предоставьте подробное описание вашего предмета, включая состояние, особенности и любые недостатки.",
    estimatedValueHelp: "Введите оценочную стоимость вашего предмета в долларах США. Это помогает сбалансировать сделку.",
    imageHelp: "Загрузите четкое изображение вашего предмета. Максимум 1 файл. (Принимаются: JPG, PNG)",
    addCashHelp: "Используйте ползунок, чтобы добавить наличные к вашему предложению. Максимальное значение будет основано на оценочной стоимости целевого предмета.",
    requestCashHelp: "Используйте ползунок, чтобы запросить наличные у другой стороны. Максимальное значение будет основано на оценочной стоимости целевого предмета.",
    sendMessagePlaceholder: "Напишите дружелюбное сообщение другой стороне, объясняющее ваше предложение.",
    tradeOfferSentSuccessfully: "Предложение об обмене успешно отправлено!",
    failedToSendOffer: "Не удалось отправить предложение об обмене.",
    preview: "Предварительный просмотр",
    lookingForHelp: "Выберите категории предметов, которые вы хотите получить в обмен. Вы можете выбрать несколько.",
    cashFlexibilityHelp: "Определите свои предпочтения по наличности. 'Готов добавить наличные' означает, что вы можете предложить наличные. 'Готов получить наличные' означает, что вы можете запросить наличные. 'И то, и другое' позволяет любой вариант. 'Только обмен' означает отсутствие наличных.",
    titleRequired: "Название обязательно.",
    categoryRequired: "Категория обязательна.",
    valueRequired: "Требуется оценочная стоимость.",
    minimumValue: "Минимальное значение — 1.",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('he');
  const [dir, setDir] = useState('ltr');

  useEffect(() => {
    const rtlLanguages = ['he', 'ar'];
    setDir(rtlLanguages.includes(language) ? 'rtl' : 'ltr');
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key, defaultValue) => {
    if (!key || typeof key !== 'string') return defaultValue || key;
    const resolve = (path, obj) => path.split('.').reduce((prev, curr) => prev ? prev[curr] : null, obj) 
    const translation = resolve(key, translations[language]) || resolve(key, translations.en);
    return translation || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  // console.log('LanguageContext value:', context); // Optional debug
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' }
];