/* eslint-disable no-useless-escape */
import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    google: "Google",
    facebook: "Facebook",
    brand: "AHLAFOT",
    tagline: "Connect. Trade. Swap.",
    heroTitle: "The Modern Way to Trade and Swap",
    heroSubtitle: "Join our community to trade items, services, and discover new opportunities every day.",
    explore: "Explore the Marketplace",
    listItem: "List an Item",
    listYourItem: 'List Your Item',
    cards: 'Cards',
    electronics: 'Electronics',
    clothing: 'Clothing',
    books: 'Books',
    orCreateNewCategory: 'Or create a new one',
    newCategoryName: 'New category name',
    addCategory: 'Add',
    category: "Category",
    categories: "Categories",
    myItems: "My Items",
    messages: "Messages",
    profile: "Profile",
    search: "Search items...",
    viewAll: 'View All',
    refresh: 'Refresh',
    light: 'Light',
    dark: 'Dark',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    menu: 'Menu',
    browseItems: 'Browse Items',
    browseServices: 'Browse Services',
    searchItems: 'Search items to swap...',
    popularItems: 'Popular Items',
    popularServices: 'Popular Services',
    suggestedForYou: 'Suggested For You',
    suggestedItems: 'Suggested Items',
    suggestedServices: 'Suggested Services',
    viewAllItems: 'View All Items',
    viewAllServices: 'View All Services',
    signIn: 'Sign In',
    register: 'Register',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    signInToAccount: 'Sign in to your account',
    orContinueWith: 'Or continue with',
    cars: 'Cars',
    motorcycles: 'Motorcycles',
    boats: 'Boats',
    realEstate: 'Real Estate',
    phones: 'Phones',
    computers: 'Computers',
    gaming: 'Gaming',
    cameras: 'Cameras',
    watches: 'Watches',
    jewelry: 'Jewelry',
    handbags: 'Handbags',
    sneakers: 'Sneakers',
    fashion: 'Fashion',
    furniture: 'Furniture',
    art: 'Art',
    pets: 'Pets',
    services: 'Services',
    crypto: 'Crypto',
    bitcoin: 'Bitcoin',
    alt: 'Alt Coins',
    meme: 'Meme Coins',
    other: 'Other',
    condition: 'Condition',
    location: 'Location',
    lookingFor: 'Looking For',
    cashFlexibility: 'Cash Option',
    estimated: 'Estimated',
    makeOffer: 'Make Offer',
    yourOffer: 'Your Offer',
    theirItem: 'Their Item',
    addCash: 'Add Cash',
    requestCash: 'Request Cash',
    viewOffer: 'View Offer',
    tradeOfferDetails: 'Trade Offer Details',
    offered: 'Offered',
    requested: 'Requested',
    offerMessage: 'Offer Message',
    status: 'Status',
    decline: 'Decline',
    acceptOffer: 'Accept Offer',
    statusUpdated: 'Trade status updated!',
    noAvailableOffers: 'No available offers yet ⌚',
    updatedOffer: 'I have updated my offer.',
    sentTradeOffer: 'Sent you a trade offer!',
    tradeOffer: 'Trade Offer',
    negotiationUpdate: 'Negotiation update...',
    sentAnImage: 'Sent an image 📷',
    sentAVoice: 'Sent a recording 🎤',
    cancelOffer: 'Cancel Offer',
    cancel: 'Cancel',
    loadingTradeDetails: 'Loading trade details...',
    errorLoadingTrade: 'Error loading trade details',
    balance: 'Balance',
    tradeOfferDescription: 'Select an item to offer, or create a new one, and/or add cash.',
    createNewItemOffer: 'Create New Item Offer',
    image: 'Image',
    title: 'Title',
    description: 'Description',
    estimatedValue: 'Estimated Value',
    new: 'New',
    likeNew: 'Like New',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    canAdd: 'Can add cash',
    canReceive: 'Can receive cash',
    canAddOrReceive: 'Can add or receive cash',
    preferExchange: 'Prefer exchange',
    Anything: 'Anything',
    'Like_new': 'Like New',
    'can_add': 'Can add cash',
    'can_receive': 'Can receive cash',
    'can_add_or_receive': 'Can add or receive cash',
    'prefer_exchange': 'Prefer exchange',
    featuredItems: 'Featured Items',
    navSearch: 'Search',
    navBrowse: 'Items',
    navServices: 'Services',
    navMessages: 'Messages',
    navProfile: 'Profile',
    navCoins: 'Coins',
    navAdmin: 'Admin',
    navLogin: 'Login',
    navRegister: 'Register',
    howItWorks: {
      title: 'How Ahlafot Works',
      step1: {
        title: '1. List Your Item',
        description: "Snap some pics, write a catchy description, and set an estimated value for your item. Make it shine!",
      },
      step2: {
        title: '2. Discover Treasures',
        description: 'Browse a world of items from other users. Use our search to find exactly what you\'re looking for. Your next find awaits.',
      },
      step3: {
        title: '3. Seal the Deal',
        description: 'Propose a swap by offering your items. You can add or request cash to balance the deal. Negotiate, agree, and get ready to swap!',
      },
    },
    active: 'Active',
    pending: 'Pending',
    countered: 'Countered',
    accepted: 'Accepted',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    completed: 'Completed',
    offer: 'Offer',
    counter: 'Counter',
    accept: 'Accept',
    reject: 'Reject',
    offerCountered: 'Offer Countered!',
    tradeAccepted: 'Trade Accepted!',
    tradeRejected: 'Trade Rejected',
    tradeCancelled: 'Trade Cancelled',
    tradeAcceptedMsg: 'Trade accepted.',
    tradeRejectedMsg: 'Trade rejected.',
    counterOfferSentMsg: 'Counter offer sent!',
    newMessageReceived: 'New message received',
    requestCashFromThem: 'Request Cash From Them',
    message: 'Message',
    newOfferTitlePlaceholder: "Enter a concise title for your item (e.g., 'Vintage Watch', 'Gaming PC')",
    newOfferDescriptionPlaceholder: "Provide a detailed description of your item, including condition, features, and any flaws.",
    estimatedValueHelp: "Enter the estimated value of your item in USD. This helps balance the trade.",
    imageHelp: "Upload a clear image of your item. Max 1 file. (Accepted: JPG, PNG)",
    addCashHelp: "Use the slider to add cash to your offer. Max value will be based on the target item's estimated value.",
    requestCashHelp: "Use the slider to request cash from the other party. Max value will be based on the target item's estimated value.",
    sendMessagePlaceholder: "Write a friendly message to the other party, explaining your offer.",
    tradeOfferSentSuccessfully: "Trade offer sent successfully!",
    serviceRequestSentSuccessfully: "Service request sent successfully!",
    failedToSendOffer: "Failed to send trade offer.",
    preview: "Preview",
    view: "View",
    cash: "cash",
    proposedTrade: "Proposed a trade",
    askingFor: "asking for",
    bookingService: "Booking Service",
    sending: "Sending...",
    sendRequest: "Send Request",
    bookingFor: "Booking for",
    negotiation: "Negotiation",
    preferredDate: "Preferred Date & Time",
    serviceMessagePlaceholder: "Describe what you need help with...",
    receiverRequired: "Receiver is required for an offer",
    cannotOfferToSelf: "You cannot make an offer on your own item!",
    lookingForHelp: "Select categories of items you are looking to receive in a trade. You can select multiple.",
    cashFlexibilityHelp: "Define your cash preferences. 'Can add cash' means you can offer cash. 'Can receive cash' means you can request cash. 'Can add or receive' allows either. 'Prefer exchange' means you prioritize trading without cash balancing.",
    titleRequired: "Title is required.",
    categoryRequired: "Category is required.",
    valueRequired: "Estimated value is required.",
    minimumValue: "Minimum value is 1.",
    quickLinks: "Quick Links",
    company: "Company",
    aboutUs: "About Us",
    careers: "Careers",
    press: "Press",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    myCoins: "My Coins",
    yourCoins: "Your Coins",
    dailyRewardInfo: "You receive 5 coins daily upon logging in.",
    nextReward: "Next reward can be claimed after:",
    nextRewardIn: "Next reward in:",
    coinUsage: "Coin Usage",
    featureItemWithCoins: "You can spend coins to feature your items. Featured items appear prominently and get more visibility.",
    featureCost: "Featuring an item costs 5 coins and lasts for 12 hours. You can feature your items from the 'My Items' page.",
    availableNow: "Available Now",
    locationPlaceholder: "e.g. Tel Aviv",
    emailAddress: "Email Address",
    email: "Email Address",
    emailRequired: "Email address is required.",
    password: "Password",
    passwordRequired: "Password is required.",
    rememberMe: "Remember me",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    registerAccount: "Register your account",
    fullName: "Full Name",
    fullNamePlaceholder: "Full Name",
    fullNameRequired: "Full Name is required.",
    emailAddressPlaceholder: "username@mail.com",
    passwordPlaceholder: "Password",
    passwordMinLength: "Password must be at least 6 characters",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm Password",
    confirmPasswordRequired: "Confirm Password is required.",
    passwordsMismatch: "Passwords do not match",
    registering: "Registering...",
    alreadyHaveAccount: "Already have an account? Sign In",
    items: "Items",
    selectCategory: "Select Category",
    loading: "Loading...",
    mainImageRequired: "Main Image (required)",
    brand: "Brand",
    brandPlaceholder: "e.g. Nike, Apple, Toyota",
    uploadAFile: "Upload a file",
    orDragAndDrop: "or drag and drop",
    imageFormats: "PNG, JPG, GIF up to 10MB",
    uploadFiles: "Upload files",
    additionalImagesOptional: "Additional Images (optional)",
    conditionRequired: "Condition is required",
    selectCondition: "Select Condition",
    selectLookingFor: "Select items you are looking for",
    lookingForOptional: "Looking For (optional)",
    listMyItem: "List My Item",
    itemsFoundSuffix: "items found",
    errorLoadingItems: "Error loading items",
    filterBy: "Filter By",
    priceRange: "Price Range",
    applyFilters: "Apply Filters",
    clearFilters: "Clear Filters",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    gridView: "Grid View",
    listView: "List View",
    categoryCreated: "Category created successfully!",
    categoryNameEmpty: "Category name cannot be empty",
    itemListedSuccess: "Item listed successfully!",
    mainImageRequiredError: "Please upload a main image for your item.",
    holdCtrl: "Hold Ctrl/Cmd to select multiple",
    selectItemsToOffer: "Select items to offer",
    noItemsToList: "You have no items listed yet.",
    cashAdjustment: "Cash Adjustment",
    iWillAddCash: "I will add cash",
    sendOffer: "Send Offer",
    offerSent: "Offer sent successfully!",
    startConversation: "Start the conversation!",
    tradeOffer: "Trade Offer",
    sendImage: "Send Image",
    typeAMessage: "Type a message...",
    sendContactInfo: "Send Contact Info",
    messageSentSuccessfully: "Message sent successfully",
    failedToSendChatMessage: "Failed to send message",
    failedToUploadMedia: "Failed to upload media",
    errorLoadingMessages: "Error loading messages",
    noMessagesFound: "No messages found",
    yourItems: "Your Items",
    iAddCash: "I Add Cash 💸",
    iRequestCash: "I Request Cash 🤲",
    none: "None",
    clear: "Clear",
    offering: "Offering",
    custom: "custom",
    customOffer: "Custom Offer",
    cancelCustomItem: "Cancel Custom Item",
    orCreateCustomOffer: "Or create a custom offer",
    tradingFor: "Trading for",
    noItemsListed: "You don't have any items listed yet.",
    basicInfo: "Basic Information",
    itemDetails: "Item Details",
    media: "Media",
    tradingPreferences: "Trading Preferences",
    editItem: "Edit Your Listing",
    editItemSubtitle: "Update your item details and photos to keep your listing fresh.",
    createItemSubtitle: "Turn your unused items into something new. Fill in the details below.",
    noItemsSelected: "No items selected",
    searchCategories: "Search categories...",
    searchServices: "Search services...",
    filters: "Filters",
    trade: "Trade",
    item: "Item",
    service: "Service",
    hourlyRate: "Hourly Rate",
    loginToTrade: "Please log in to make a trade offer.",
    claimReward: "Claim Daily Reward",
    claimRewardSuccess: "You claimed {amount} coins!",
    contactSupport: "Contact Support",
    browseItemsSubtitle: "Discover unique items to trade",
    browseServicesSubtitle: "Find professionals for your needs",
    upTo: "Up to",
    clearAll: "Clear All",
    noItemsFoundMatching: "No items found matching your criteria.",
    noServicesFound: "No services found.",
    perHour: "/hr",
    flexible: "Flexible",
    notSpecified: "Not specified",
    secure: "Secure",
    secureTrading: "Secure Trading",
    activeBadge: "Active",
    activeCommunity: "Active Community",
    fast: "Fast",
    fastSwapping: "Fast Swapping",
    openToOtherOffers: "Open to other offers",
    openToOtherOffersDesc: "Check this if you are willing to hear offers outside your preferred categories.",
    timeToUpgrade: "Time to upgrade!",
    doNotShowAgain: "Do not show again",
    back: "Back",
    backToSearch: "Back to Search",
    pageInfo: "Page Information",
    howToUse: "How to Use",
    tradeDeckInfo: {
        title: "Trade Offer Window",
        description: "Select items from your collection to offer in exchange. You can also add or request cash to balance the deal. Double-tap any item image to see its full details before deciding!"
    },
    browseInfo: {
        title: "Browse Items",
        description: "Explore all items available for trade. Use filters to narrow down by category, price, or location. Click an item to see more details and make an offer."
    },
    servicesInfo: {
        title: "Browse Services",
        description: "Find professionals offering their services in exchange for items or other services. You can book a service by proposing a trade."
    },
    myItemsInfo: {
        title: "My Items",
        description: "Manage your listed items here. You can edit, delete, or feature them to get more visibility using your coins."
    },
    messagesInfo: {
        title: "Offers & Messages",
        description: "Track all your active trade negotiations. Each conversation represents a potential trade. Use the Negotiation Room to finalize details."
    },
    profileInfo: {
        title: "User Profile",
        description: "Update your personal information, change your avatar, and see your trading statistics and history."
    },
    coinPanelInfo: {
        title: "Coin Center",
        description: "Check your coin balance and claim your daily reward. Use coins to feature your items and get 10x more offers!"
    },
    adminInfo: {
        title: "Admin Dashboard",
        description: "System management area. Monitor trades, users, and categories to ensure a safe and active community."
    },
    mutualMatches: "Mutual Matches",
    mutualMatchesDesc: "Items from users looking for what you have! Perfect for a straight swap.",
    share: "Share",
    shareItem: "Share an Item",
    noItemsToShare: "No items to share.",
    shareItemLink: "Share Item Link",
    scheduleDate: "Schedule Date",
    availability: 'Availability',
    reviews: 'Reviews',
    verifiedClient: 'Verified Client',
    noReviewsYet: 'No reviews yet. Be the first to share your experience!',
    writeAReview: 'Write a Review',
    shareExperience: 'Share your experience...',
    similarItems: 'Similar Items',
    moreInThisCategory: 'More in this category',
    owner: 'Owner',
    website: 'Website',
    instagram: 'Instagram',
    googleReviews: 'Google Reviews',
    noOffersFound: 'No active offers found',
    startTradingPrompt: 'Find items you love and send an offer to start negotiating!',
    yourOffers: 'Offer Center',
    selectOfferPrompt: 'Select an offer from the sidebar to view details and negotiate.',
    negotiatePrompt: 'Write a message about this offer...',
    startChatPrompt: 'No messages in this offer yet',
    searchOffers: 'Filter offers...',
    offers: 'Offers',
    supportChat: 'Ahlafot Support',
    askHelp: 'Need help?',
    accept: 'Accept',
    counterOffer: 'Counter Offer',
    typing: 'typing...',
    online: 'Online',
    offline: 'Offline',
    you: 'You',
    openNegotiation: 'Open Negotiation',
    negotiationRoom: 'Negotiation Room',
    tradeSummary: 'Offer Summary',
    noActiveNegotiation: 'No active negotiation',
    backToOffers: 'Back to Offers',
    viewItems: 'View Items',
    chatWithUser: 'Chat with User',
    systemMessage: 'System Message',
    newOfferReceived: 'New Offer Received!',
    openToViewAndChat: 'Open to view items and talk',
    offerRemovedFromChat: 'Offer removed from the chat',
    authFailed: 'Authentication failed',
    invalidEmailPassword: 'Invalid email or password',
    loginSuccess: 'Logged in successfully!',
    registerSuccess: 'Registered successfully!',
    registrationFailed: 'Registration failed',
    participantNotFound: 'Other participant not found',
    cannotChatSelf: 'Cannot chat with yourself',
    itemNotFound: 'Item not found',
  },
  he: {
    google: "Google",
    brand: "AHLAFOT",
    tagline: "שדרג את העולם שלך. החלפות.",
    heroSubtitle: "מרכבי אספנות ועד טכנולוגיה עילית—גלה עולם של ערך שמחכה רק לך.",
    explore: "חקור עסקאות",
    listItem: "הוסף פריט",
    listYourItem: "הוסף את הפריט שלך",
    cards: "קלפים",
    electronics: "אלקטרוניקה",
    clothing: "ביגוד",
    books: "ספרים",
    orCreateNewCategory: "או צור קטגוריה חדשה",
    newCategoryName: "שם קטגוריה חדשה",
    addCategory: "הוסף",
    category: "קטגוריה",
    categories: "קטגוריות",
    myItems: "הפריטים שלי",
    messages: "הודעות",
    profile: "פרופיל",
    search: "חפש פריטים...",
    viewAll: 'הצג הכל',
    refresh: 'רענן',
    light: 'יום',
    dark: 'לילה',
    admin: 'מנהל',
    login: 'התחבר',
    logout: 'התנתק',
    menu: 'תפריט',
    browseItems: 'עיין בפריטים',

    browseServices: 'עיון בשירותים',
    signIn: 'התחבר',
    register: 'הירשם',
    editProfile: 'ערוך פרופיל',
    saveChanges: 'שמור שינויים',
    signInToAccount: 'התחבר לחשבונך',
    orContinueWith: 'או המשך באמצעות',
    heroTitle: "הדרך המודרנית למסחר והחלפות",
    cars: 'מכוניות',
    motorcycles: 'אופנועים',
    boats: 'סירות',
    realEstate: 'נדל"ן',
    phones: 'טלפונים',
    computers: 'מחשבים',
    gaming: 'גיימינג',
    cameras: 'מצלמות',
    watches: 'שעונים',
    jewelry: 'תכשיטים',
    handbags: 'תיקים',
    sneakers: 'נעלי ספורט',
    fashion: 'אופנה',
    furniture: 'ריהוט',
    art: 'אמנות',
    pets: 'חיות מחמד',
    services: 'שירותים',
    crypto: 'קריפטו',
    bitcoin: 'ביטקוין / מטבעות ראשיים',
    alt: 'מטבעות אלטרנטיביים (Alt)',
    meme: 'מטבעות מים (Meme)',
    other: 'אחר',
    condition: 'מצב',
    location: 'מיקום',
    lookingFor: 'מחפש/ת',
    cashFlexibility: 'מעוניין בכסף',
    estimated: 'שווי מוערך',
    makeOffer: 'הצע הצעה',
    yourOffer: 'ההצעה שלך',
    theirItem: 'הפריט שלהם',
    addCash: 'הוסף כסף',
    requestCash: 'בקש כסף',
    viewOffer: 'צפה בהצעה',
    tradeOfferDetails: 'פרטי הצעת ההחלפה',
    offered: 'הוצע',
    requested: 'נתבקש',
    offerMessage: 'הודעת הצעה',
    status: 'סטטוס',
    decline: 'דחה',
    acceptOffer: 'קבל הצעה',
    statusUpdated: 'הטרייד עודכן!',
    noAvailableOffers: 'אין הצעות זמינות כרגע ⌚',
    updatedOffer: 'עדכנתי את ההצעה שלי.',
    sentTradeOffer: 'שלחתי לך הצעת טרייד!',
    tradeOffer: 'הצעת טרייד',
    negotiationUpdate: 'עדכון במשא ומתן...',
    sentAnImage: 'שלח/ה תמונה 📷',
    sentAVoice: 'שלח/ה הקלטה 🎤',
    cancelOffer: 'בטל הצעה',

    cancel: 'ביטול',
    loadingTradeDetails: 'טוען פרטי הצעה...',
    errorLoadingTrade: 'שגיאה בטעינת פרטי ההצעה',
    balance: 'איזון',
    tradeOfferDescription: 'בחר פריט להציע, או צור חדש, ו/או הוסף כסף.',
    createNewItemOffer: 'צור הצעת פריט חדש',
    image: 'תמונה',
    title: 'כותרת',
    description: 'תיאור',
    estimatedValue: 'שווי מוערך',
    new: 'חדש',
    likeNew: 'כמו חדש',
    excellent: 'מצוין',
    good: 'טוב',
    fair: 'סביר',
    canAdd: 'אפשר להוסיף',
    canReceive: 'אפשר לקבל',
    canAddOrReceive: 'מעוניין לקבל/להוסיף',
    preferExchange: 'מעדיף החלפה',
    Anything: 'הכל',
    'Like_new': 'כמו חדש',
    'like_new': 'כמו חדש',
    'can_add': 'אפשר להוסיף',
    'can_receive': 'אפשר לקבל',
    'can_add_or_receive': 'מעוניין לקבל/להוסיף',
    'prefer_exchange': 'מעדיף החלפה',
    featuredItems: 'פריטים נבחרים',
    navSearch: 'חיפוש',
    navBrowse: 'פריטים',
    navServices: 'שירותים',
    navMessages: 'הודעות',
    navProfile: 'פרופיל',
    navCoins: 'מטבעות',
    navAdmin: 'ניהול',
    navLogin: 'התחברות',
    navRegister: 'הרשמה',
    howItWorks: {
      title: 'איך החלפות עובד',
      step1: {
        title: '1. הציגו את הפריט שלכם',
        description: "צלמו כמה תמונות, כתבו תיאור מושך וקבעו שווי מוערך לפריט שלכם. גרמו לו לבלוט!",
      },
      step2: {
        title: '2. גלו אוצרות',
        description: 'דפדפו בעולם של פריטים ממשתמשים אחרים. השתמשו בחיפוש שלנו כדי למצוא בדיוק את מה שאתם מחפשים. המציאה הבאה שלכם מחכה.',
      },
      step3: {
        title: '3. סגרו עסקה',
        description: 'הציעו החלפה על ידי הצעת הפריטים שלכם. תוכלו להוסיף או לבקש כסף כדי לאזן את העסקה. נהלו משא ומתן, הסכימו והתכוננו להחלפה!',
      },
    },
    active: 'פעיל',
    pending: 'ממתין',
    countered: 'הצעה נגדית',
    accepted: 'התקבל',
    rejected: 'נדחה',
    cancelled: 'בוטל',
    completed: 'הושלם',
    offer: '',
    counter: 'נגדית',
    accept: 'אושרה',
    reject: 'נדחתה',
    offerCountered: 'הצעה נגדית נשלחה!',
    tradeAccepted: 'הטרייד אושר!',
    tradeRejected: 'הטרייד נדחה',
    tradeCancelled: 'הטרייד בוטל',
    tradeAcceptedMsg: 'הטרייד אושר.',
    tradeRejectedMsg: 'הטרייד נדחה.',
    counterOfferSentMsg: 'הצעה נגדית נשלחה!',
    newMessageReceived: 'התקבלה הודעה חדשה',
    requestCashFromThem: 'בקש מהם כסף',
    message: 'הודעה',
    newOfferTitlePlaceholder: "הכנס כותרת תמציתית לפריט שלך (לדוגמה, 'שעון וינטג', 'מחשב גיימינג')",
    newOfferDescriptionPlaceholder: "ספק תיאור מפורט של הפריט שלך, כולל מצב, תכונות וכל פגמים.",
    estimatedValueHelp: "הכנס את השווי המוערך של הפריט שלך בדולר. זה עוזר לאזן את העסקה.",
    imageHelp: "העלה תמונה ברורה של הפריט שלך. קובץ אחד מקסימום. (פורמטים נתמכים: JPG, PNG)",
    addCashHelp: "השתמש בסליידר כדי להוסיף כסף להצעה שלך. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
    requestCashHelp: "השתמש בסליידר כדי לבקש כסף מהצד השני. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
    sendMessagePlaceholder: "כתוב הודעה ידידותית לצד השני, הסבר את הצעתך.",
    tradeOfferSentSuccessfully: "הצעת החלפה נשלחה בהצלחה!",
    serviceRequestSentSuccessfully: "בקשת השירות נשלחה בהצלחה!",
    failedToSendOffer: "שליחת הצעת החלפה נכשלה.",
    preview: "תצוגה מקדימה",
    view: "צפה",
    cash: "כסף",
    proposedTrade: "הציע/ה החלפה",
    askingFor: "מבקש/ת",
    bookingService: "הזמנת שירות",
    sending: "שולח...",
    sendRequest: "שלח בקשה",
    bookingFor: "הזמנה עבור",
    negotiation: "משא ומתן",
    preferredDate: "תאריך ושעה מועדפים",
    serviceMessagePlaceholder: "תאר במה אתה זקוק לעזרה...",
    receiverRequired: "נדרש נמען להצעה",
    cannotOfferToSelf: "אינך יכול להגיש הצעה לפריט של עצמך!",
    lookingForHelp: "בחר קטגוריות של פריטים שאתה מחפש לקבל בהחלפה. באפשרותך לבחור מספר קטגוריות.",
    cashFlexibilityHelp: "הגדר/י את העדפות הכסף שלך. 'אפשר להוסיף' אומר שניתן להוסיף כסף לעסקה. 'אפשר לקבל' אומר שניתן לבקש כסף מהצד השני. 'מעוניין לקבל/להוסיף' מאפשר את שניהם. 'מעדיף החלפה' אומר עדיפות להחלפת פריטים ללא מעורבות כסף.",
    titleRequired: "נדרשת כותרת.",
    categoryRequired: "נדרשת קטגוריה.",
    valueRequired: "נדרש שווי מוערך.",
    minimumValue: "הערך המינימלי הוא 1.",
    quickLinks: "קישורים מהירים",
    company: "החברה",
    aboutUs: "אודותינו",
    careers: "קריירה",
    press: "עיתונות",
    legal: "משפטי",
    termsOfService: "תנאי שימוש",
    privacyPolicy: "מדיניות פרטיות",
    myCoins: "המטבעות שלי",
    yourCoins: "המטבעות שלך",
    dailyRewardInfo: "אתה מקבל 5 מטבעות מדי יום בהתחברות.",
    nextReward: "התגמול הבא יהיה זמין ב:",
    nextRewardIn: "התגמול הבא בעוד:",
    coinUsage: "שימוש במטבעות",
    featureItemWithCoins: "אתה יכול להשתמש במטבעות כדי להבליט את הפריטים שלך. פריטים מובלטים מופיעים באופן בולט ומקבלים יותר נראות.",
    featureCost: "הבלטת פריט עולה 5 מטבעות ונמשכת 12 שעות. אתה יכול להבליט את הפריטים שלך מדף 'הפריטים שלי'.",
    availableNow: "זמין כעת",
    locationPlaceholder: "לדוגמה, תל אביב",
    emailAddress: "כתובת אימייל",
    email: "כתובת אימייל",
    emailRequired: "נדרשת כתובת אימייל.",
    password: "סיסמה",
    passwordRequired: "נדרשת סיסמה.",
    rememberMe: "זכור אותי",
    signingIn: "מתחבר...",
    noAccount: "אין לך חשבון?",
    haveAccount: "כבר יש לך חשבון?",
    registerAccount: "רשום את חשבונך",
    fullName: "שם מלא",
    fullNamePlaceholder: "ישראל ישראלי",
    fullNameRequired: "נדרש שם מלא.",
    phoneNumber: "מספר טלפון",
    phoneNumberPlaceholder: "מספר טלפון",
    phoneNumberRequired: "מספר טלפון הוא שדה חובה",
    emailAddressPlaceholder: "username@mail.com",
    passwordPlaceholder: "סיסמה",
    passwordMinLength: "הסיסמה חייבת להיות באורך של 6 תווים לפחות",
    confirmPassword: "אישור סיסמה",
    confirmPasswordPlaceholder: "אישור סיסמה",
    confirmPasswordRequired: "נדרש אישור סיסמה.",
    passwordsMismatch: "הסיסמאות אינן תואמות",
    registering: "רושם...",
    alreadyHaveAccount: "כבר יש לך חשבון? התחבר",
    items: "פריטים",
    selectCategory: "בחר קטגוריה",
    loading: "טוען...",
    mainImageRequired: "תמונה ראשית (חובה)",
    brand: "מותג",
    brandPlaceholder: "לדוגמה: נייקי, אפל, טויוטה",
    uploadAFile: "העלה קובץ",
    orDragAndDrop: "או גרור ושחרר",
    imageFormats: "PNG, JPG, GIF עד 10MB",
    uploadFiles: "העלה קבצים",
    additionalImagesOptional: "תמונות נוספות (אופציונלי)",
    conditionRequired: "מצב הפריט נדרש",
    selectCondition: "בחר מצב",
    selectLookingFor: "בחר פריטים שאתה מחפש",
    lookingForOptional: "מחפש (אופציונלי)",
    listMyItem: "פרסם את הפריט שלי",
    itemsFoundSuffix: "פריטים נמצאו",
    errorLoadingItems: "שגיאה בטעינת פריטים",
    filterBy: "סינון לפי",
    priceRange: "טווח מחירים",
    applyFilters: "החל סינון",
    clearFilters: "נקה סינון",
    minPrice: "מחיר מינימום",
    maxPrice: "מחיר מקסימום",
    gridView: "תצוגת רשת",
    listView: "תצוגת רשימה",
    categoryCreated: "הקטגוריה נוצרה בהצלחה!",
    categoryNameEmpty: "שם הקטגוריה לא יכול להיות ריק",
    itemListedSuccess: "הפריט פורסם בהצלחה!",
    mainImageRequiredError: "אנא העלה תמונה ראשית לפריט שלך.",
    holdCtrl: "החזק Ctrl/Cmd כדי לבחור מרובים",
    selectItemsToOffer: "בחר פריטים להצעה",
    noItemsToList: "עדיין לא פרסמת פריטים.",
    cashAdjustment: "התאמת כסף",
    iWillAddCash: "אני אוסיף כסף",
    iRequestCash: "אני מבקש כסף 🤲",
    sendOffer: "שלח הצעה",
    offerSent: "ההצעה נשלחה בהצלחה!",
    startConversation: "התחל את השיחה!",
    tradeOffer: "הצעת החלפה",
    sendImage: "שלח תמונה",
    typeAMessage: "כתוב הודעה...",
    sendContactInfo: "שלח פרטי קשר",
    messageSentSuccessfully: "ההודעה נשלחה בהצלחה",
    failedToSendChatMessage: "שליחת ההודעה נכשלה",
    failedToUploadMedia: "העלאת המדיה נכשלה",
    errorLoadingMessages: "שגיאה בטעינת הודעות",
    noMessagesFound: "לא נמצאו הודעות",
    yourItems: "הפריטים שלך",
    iAddCash: "אני מוסיף כסף 💸",
    none: "ללא",
    clear: "נקה",
    offering: "מציע",
    custom: "נוסף",
    customOffer: "הצעה מותאמת אישית",
    cancelCustomItem: "בטל פריט מותאם",
    orCreateCustomOffer: "או צור הצעה מותאמת אישית",
    tradingFor: "מחליף עבור",
    noItemsListed: "אין לך פריטים רשומים עדיין.",
    basicInfo: "מידע בסיסי",
    itemDetails: "פרטי הפריט",
    media: "מדיה",
    tradingPreferences: "העדפות מסחר",
    editItem: "עריכת הפריט שלך",
    editItemSubtitle: "עדכן את פרטי הפריט והתמונות כדי לשמור על המודעה שלך מעודכנת.",
    createItemSubtitle: "הפוך את הפריטים שאינך בשימוש למשהו חדש. מלא את הפרטים למטה.",
    noItemsSelected: "לא נבחרו פריטים",
    searchCategories: "חפש קטגוריות...",
    searchServices: "חפש שירותים...",
    searchItems: "חפש פריטים להחלפה...",
    popularItems: "פריטים פופולריים",
    popularServices: "שירותים פופולריים",
    suggestedForYou: "הצעות עבורך:",
    suggestedItems: "פריטים מומלצים",
    suggestedServices: "שירותים מומלצים",
    filters: "סינון",
    trade: "טרייד",
    item: "פריט",
    service: "שירות",
    hourlyRate: "מחיר לשעה",
    loginToTrade: "אנא התחבר כדי להגיש הצעת החלפה.",
    claimReward: "קבל בונוס יומי",
    claimRewardSuccess: "קיבלת {amount} מטבעות!",
    contactSupport: "צור קשר עם תמיכה",
    browseItemsSubtitle: "גלה פריטים ייחודיים להחלפה",
    browseServicesSubtitle: "מצא אנשי מקצוע לצרכים שלך",
    upTo: "עד",
    clearAll: "נקה הכל",
    noItemsFoundMatching: "לא נמצאו פריטים המתאימים לקריטריונים שלך.",
    noServicesFound: "לא נמצאו שירותים.",
    perHour: "/שעה",
    flexible: "גמיש",
    notSpecified: "לא צוין",
    secure: "מאובטח",
    secureTrading: "מסחר בטוח",
    activeBadge: "פעיל",
    activeCommunity: "קהילה פעילה",
    fast: "מהיר",
    fastSwapping: "החלפות מהירות",
    openToOtherOffers: "פתוח להצעות אחרות",
    openToOtherOffersDesc: "סמן אם אתה מוכן לשמוע הצעות שאינן מהקטגוריות שבחרת.",
    timeToUpgrade: "הגיע הזמן להתחדש!",
    doNotShowAgain: "אל תראה שוב",
    back: 'חזור',
    backToSearch: 'חזרה לחיפוש',
    pageInfo: "מידע על הדף",
    howToUse: "איך להשתמש",
    tradeDeckInfo: {
        title: "חלון הצעת טרייד",
        description: "בחרו פריטים מהאוסף שלכם להצעה בתמורה. ניתן גם להוסיף או לבקש כסף כדי לאזן את העסקה. דאבל-קליק (לחיצה כפולה) על תמונת פריט תפתח את הפרטים המלאים שלו לפני שתחליטו!"
    },
    browseInfo: {
        title: "עיון בפריטים",
        description: "חקרו את כל הפריטים הזמינים להחלפה. השתמשו במסננים כדי לצמצם לפי קטגוריה, מחיר או מיקום. לחצו על פריט כדי לראות פרטים נוספים ולהציע הצעה."
    },
    servicesInfo: {
        title: "עיון בשירותים",
        description: "מצאו אנשי מקצוע המציעים את שירותיהם בתמורה לפריטים או שירותים אחרים. ניתן להזמין שירות על ידי הצעה לטרייד."
    },
    myItemsInfo: {
        title: "הפריטים שלי",
        description: "נהלו את הפריטים שפרסמתם כאן. ניתן לערוך, למחוק או להבליט אותם כדי לקבל יותר חשיפה באמצעות המטבעות שלכם."
    },
    messagesInfo: {
        title: "הצעות והודעות",
        description: "עקבו אחר כל המשא ומתן הפעיל שלכם. כל שיחה מייצגת טרייד פוטנציאלי. השתמשו בחדר המשא ומתן כדי לסגור פרטים."
    },
    profileInfo: {
        title: "פרופיל משתמש",
        description: "עדכנו את המידע האישי שלכם, שנו את האוואטר שלכם וראו את הסטטיסטיקה והיסטוריית המסחר שלכם."
    },
    coinPanelInfo: {
        title: "מרכז המטבעות",
        description: "בדקו את יתרת המטבעות שלכם וקבלו את התגמול היומי. השתמשו במטבעות כדי להבליט את הפריטים שלכם ולקבל פי 10 יותר הצעות!"
    },
    adminInfo: {
        title: "לוח בקרה למנהל",
        description: "אזור ניהול המערכת. עקבו אחר טריידים, משתמשים וקטגוריות כדי להבטיח קהילה בטוחה ופעילה."
    },
    mutualMatches: "הצעות להתאמה",
    mutualMatchesDesc: "פריטים של משתמשים שמחפשים בדיוק את מה שיש לך! מושלם להחלפה ישירה.",
    share: 'שתף',
    shareItem: "שתף פריט",
    noItemsToShare: "אין פריטים לשתף.",
    shareItemLink: "שתף קישור לפריט",
    scheduleDate: "תיאום תאריך",
    availability: 'זמינות',
    reviews: 'ביקורות',
    verifiedClient: 'לקוח מאומת',
    noReviewsYet: 'אין ביקורות עדיין. היו הראשונים לשתף את החוויה שלכם!',
    writeAReview: 'כתיבת ביקורת',
    shareExperience: 'שתף את החוויה שלך...',
    similarItems: 'פריטים דומים',
    moreInThisCategory: 'עוד בקטגוריה זו',
    owner: 'בעלים',
    website: 'אתר אינטרנט',
    instagram: 'אינסטגרם',
    facebook: 'פייסבוק',
    googleReviews: 'Google Reviews',
    noOffersFound: 'לא נמצאו הצעות פעילות',
    startTradingPrompt: 'מצא פריטים שאתה אוהב ושלח הצעה כדי להתחיל במשא ומתן!',
    yourOffers: 'מרכז ההצעות',
    selectOfferPrompt: 'בחר הצעה מהסרגל הצידי כדי לצפות בפרטים ולנהל משא ומתן.',
    negotiatePrompt: 'כתוב הודעה לגבי הצעה זו...',
    startChatPrompt: 'אין עדיין הודעות בהצעה זו',
    searchOffers: 'סינון הצעות...',
    offers: 'הצעות',
    supportChat: 'תמיכת Ahlafot',
    askHelp: 'צריך עזרה?',
    accept: 'קבל',
    counterOffer: 'הצעה נגדית',
    typing: 'מקליד/ה...',
    online: 'מחובר/ת',
    offline: 'מנותק/ת',
    you: 'אני',
    openNegotiation: 'פתח חלון משא ומתן',
    negotiationRoom: 'חדר משא ומתן',
    tradeSummary: 'סיכום הצעה',
    noActiveNegotiation: 'אין משא ומתן פעיל',
    backToOffers: 'חזרה להצעות',
    viewItems: 'צפה בפריטים',
    chatWithUser: 'צ׳אט עם המשתמש',
    systemMessage: 'הודעת מערכת',
    newOfferReceived: 'התקבלה הצעה חדשה!',
    openToViewAndChat: 'פתח כדי לצפות בפריטים ולדבר',
    offerRemovedFromChat: 'ההצעה הוסרה על ידי אחד הצדדים.',
    authFailed: 'האימות נכשל',
    invalidEmailPassword: 'אימייל או סיסמה שגויים',
    loginSuccess: 'התחברת בהצלחה!',
    registerSuccess: 'נרשמת בהצלחה!',
    registrationFailed: 'ההרשמה נכשלה',
    participantNotFound: 'המשתמש השני לא נמצא',
    cannotChatSelf: 'אינך יכול לשלוח הודעה לעצמך',
    itemNotFound: 'הפריט לא נמצא',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'he');
  const [dir, setDir] = useState('rtl');

  useEffect(() => {
    localStorage.setItem('language', language);
    const rtlLanguages = ['he'];
    const newDir = rtlLanguages.includes(language) ? 'rtl' : 'ltr';
    setDir(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, defaultValue) => {
    if (!key || typeof key !== 'string') return defaultValue || key;
    const resolve = (path, obj) => path.split('.').reduce((prev, curr) => prev ? prev[curr] : null, obj) 
    
    let translation = resolve(key, translations[language]);
    if (translation === undefined || translation === null) {
        translation = resolve(key, translations.en);
    }
    
    return (translation !== undefined && translation !== null) ? translation : (defaultValue || key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' },
];
