/* eslint-disable no-useless-escape */
import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brand: "SwapX",
    tagline: "Connect. Trade. Swap.",
    heroTitle: "The Modern Way to Trade and Swap",
    heroSubtitle: "Join our community to trade items, services, and discover new opportunities every day.",
    explore: "Explore the Marketplace",
    listItem: "List an Item",
    listYourItem: 'List Your Item',
    cards: 'Cards',
    electronics: 'Electronics',
    clothing: 'Clothing',
    books: 'Books',
    orCreateNewCategory: 'Or create a new one',
    newCategoryName: 'New category name',
    addCategory: 'Add',
    category: "Category",
    categories: "Categories",
    myItems: "My Items",
    messages: "Messages",
    profile: "Profile",
    search: "Search items...",
    viewAll: 'View All',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    browseItems: 'Browse Items',
    browseServices: 'Browse Services',
    searchItems: 'Search items to swap...',
    searchServices: 'Search services...',
    popularItems: 'Popular Items',
    popularServices: 'Popular Services',
    suggestedForYou: 'Suggested For You',
    suggestedItems: 'Suggested Items',
    suggestedServices: 'Suggested Services',
    viewAllItems: 'View All Items',
    viewAllServices: 'View All Services',
    signIn: 'Sign In',
    register: 'Register',
    editProfile: 'Edit Profile',
    cars: 'Cars',
    motorcycles: 'Motorcycles',
    boats: 'Boats',
    realEstate: 'Real Estate',
    phones: 'Phones',
    computers: 'Computers',
    gaming: 'Gaming',
    cameras: 'Cameras',
    watches: 'Watches',
    jewelry: 'Jewelry',
    handbags: 'Handbags',
    sneakers: 'Sneakers',
    fashion: 'Fashion',
    furniture: 'Furniture',
    art: 'Art',
    pets: 'Pets',
    services: 'Services',
    other: 'Other',
    condition: 'Condition',
    location: 'Location',
    lookingFor: 'Looking For',
    cashFlexibility: 'Cash Flexibility',
    estimated: 'Estimated',
    makeOffer: 'Make Offer',
    yourOffer: 'Your Offer',
    theirItem: 'Their Item',
    addCash: 'Add Cash',
    requestCash: 'Request Cash',
    sendOffer: 'Send Offer',
    balance: 'Balance',
    tradeOfferDescription: 'Select an item to offer, or create a new one, and/or add cash.',
    createNewItemOffer: 'Create New Item Offer',
    image: 'Image',
    title: 'Title',
    description: 'Description',
    estimatedValue: 'Estimated Value',
    new: 'New',
    likeNew: 'Like New',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    willingToAdd: 'Willing to add cash',
    willingToReceive: 'Willing to receive cash',
    both: 'Both',
    tradeOnly: 'Trade Only',
    Anything: 'Anything',
    'Like_new': 'Like New',
    'willing_to_add': 'Willing to add cash',
    'willing_to_receive': 'Willing to receive cash',
    'trade_only': 'Trade Only',
    featuredItems: 'Featured Items',
    howItWorks: {
      title: 'How SwapX Works',
      step1: {
        title: '1. List Your Item',
        description: "Snap some pics, write a catchy description, and set an estimated value for your item. Make it shine!",
      },
      step2: {
        title: '2. Discover Treasures',
        description: 'Browse a world of items from other users. Use our search to find exactly what you\'re looking for. Your next find awaits.',
      },
      step3: {
        title: '3. Seal the Deal',
        description: 'Propose a swap by offering your items. You can add or request cash to balance the deal. Negotiate, agree, and get ready to swap!',
      },
    },
    active: 'Active',
    pending: 'Pending',
    requestCashFromThem: 'Request Cash From Them',
    message: 'Message',
    newOfferTitlePlaceholder: "Enter a concise title for your item (e.g., 'Vintage Watch', 'Gaming PC')",
    newOfferDescriptionPlaceholder: "Provide a detailed description of your item, including condition, features, and any flaws.",
    estimatedValueHelp: "Enter the estimated value of your item in USD. This helps balance the trade.",
    imageHelp: "Upload a clear image of your item. Max 1 file. (Accepted: JPG, PNG)",
    addCashHelp: "Use the slider to add cash to your offer. Max value will be based on the target item's estimated value.",
    requestCashHelp: "Use the slider to request cash from the other party. Max value will be based on the target item's estimated value.",
    sendMessagePlaceholder: "Write a friendly message to the other party, explaining your offer.",
    tradeOfferSentSuccessfully: "Trade offer sent successfully!",
    failedToSendOffer: "Failed to send trade offer.",
    preview: "Preview",
    lookingForHelp: "Select categories of items you are looking to receive in a trade. You can select multiple.",
    cashFlexibilityHelp: "Define your cash preferences. 'Willing to add cash' means you can offer cash. 'Willing to receive cash' means you can request cash. 'Both' allows either. 'Trade only' means no cash involved.",
    titleRequired: "Title is required.",
    categoryRequired: "Category is required.",
    valueRequired: "Estimated value is required.",
    minimumValue: "Minimum value is 1.",
    quickLinks: "Quick Links",
    company: "Company",
    aboutUs: "About Us",
    careers: "Careers",
    press: "Press",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    myCoins: "My Coins",
    yourCoins: "Your Coins",
    dailyRewardInfo: "You receive 5 coins daily upon logging in.",
    nextReward: "Next reward can be claimed after:",
    coinUsage: "Coin Usage",
    featureItemWithCoins: "You can spend coins to feature your items. Featured items appear prominently and get more visibility.",
    featureCost: "Featuring an item costs 5 coins and lasts for 12 hours. You can feature your items from the 'My Items' page.",
    availableNow: "Available Now",
    locationPlaceholder: "e.g. Tel Aviv",
    emailAddress: "Email Address",
    emailRequired: "Email address is required.",
    password: "Password",
    passwordRequired: "Password is required.",
    signingIn: "Signing in...",
    noAccount: "Don't have an account? Sign Up",
    registerAccount: "Register your account",
    fullName: "Full Name",
    fullNamePlaceholder: "Full Name",
    fullNameRequired: "Full Name is required.",
    emailAddressPlaceholder: "Email Address",
    passwordPlaceholder: "Password",
    passwordMinLength: "Password must be at least 6 characters",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm Password",
    confirmPasswordRequired: "Confirm Password is required.",
    passwordsMismatch: "Passwords do not match",
    registering: "Registering...",
    alreadyHaveAccount: "Already have an account? Sign In",
    items: "Items",
    selectCategory: "Select Category",
    loading: "Loading...",
    mainImageRequired: "Main Image (required)",
    uploadAFile: "Upload a file",
    orDragAndDrop: "or drag and drop",
    imageFormats: "PNG, JPG, GIF up to 10MB",
    uploadFiles: "Upload files",
    additionalImagesOptional: "Additional Images (optional)",
    conditionRequired: "Condition is required",
    selectCondition: "Select Condition",
    selectLookingFor: "Select items you are looking for",
    lookingForOptional: "Looking For (optional)",
    listMyItem: "List My Item",
    itemsFoundSuffix: "items found",
    errorLoadingItems: "Error loading items",
    filterBy: "Filter By",
    priceRange: "Price Range",
    applyFilters: "Apply Filters",
    clearFilters: "Clear Filters",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    gridView: "Grid View",
    listView: "List View",
    categoryCreated: "Category created successfully!",
    categoryNameEmpty: "Category name cannot be empty",
    itemListedSuccess: "Item listed successfully!",
    mainImageRequiredError: "Please upload a main image for your item.",
    holdCtrl: "Hold Ctrl/Cmd to select multiple",
    selectItemsToOffer: "Select items to offer",
    noItemsToList: "You have no items listed yet.",
    cashAdjustment: "Cash Adjustment",
    iWillAddCash: "I will add cash",
    iRequestCash: "I request cash",
    sendOffer: "Send Offer",
    offerSent: "Offer sent successfully!",
    startConversation: "Start the conversation!",
    tradeOffer: "Trade Offer",
    sendImage: "Send Image",
    typeAMessage: "Type a message...",
    sendContactInfo: "Send Contact Info",
    messageSentSuccessfully: "Message sent successfully",
    failedToSendChatMessage: "Failed to send message",
    failedToUploadMedia: "Failed to upload media",
    errorLoadingMessages: "Error loading messages",
    noMessagesFound: "No messages found",
    yourItems: "Your Items",
    iAddCash: "I Add Cash 💸",
    iRequestCash: "I Request Cash 🤲",
    none: "None",
    clear: "Clear",
    offering: "Offering",
    customOffer: "Custom Offer",
    cancelCustomItem: "Cancel Custom Item",
    orCreateCustomOffer: "Or create a custom offer",
    tradingFor: "Trading for",
    noItemsListed: "You don't have any items listed yet.",
    basicInfo: "Basic Information",
    itemDetails: "Item Details",
    media: "Media",
    tradingPreferences: "Trading Preferences",
    createItemSubtitle: "Turn your unused items into something new. Fill in the details below.",
    noItemsSelected: "No items selected",
    searchCategories: "Search categories...",
    searchServices: "Search services...",
    filters: "Filters",
    item: "Item",
    service: "Service",
    hourlyRate: "Hourly Rate",
    loginToTrade: "Please log in to make a trade offer.",
    claimReward: "Claim Daily Reward",
    contactSupport: "Contact Support",
    browseItemsSubtitle: "Discover unique items to trade",
    browseServicesSubtitle: "Find professionals for your needs",
    upTo: "Up to",
    clearAll: "Clear All",
    noItemsFoundMatching: "No items found matching your criteria.",
    noServicesFound: "No services found.",
    perHour: "/hr",
    flexible: "Flexible",
    notSpecified: "Not specified",
  },
  he: {
    brand: "SwapX",
    tagline: "שדרג את העולם שלך. סוואפ-אקס.",
    heroSubtitle: "מרכבי אספנות ועד טכנולוגיה עילית—גלה עולם של ערך שמחכה רק לך.",
    explore: "חקור עסקאות",
    listItem: "הוסף פריט",
    listYourItem: "הוסף את הפריט שלך",
    cards: "קלפים",
    electronics: "אלקטרוניקה",
    clothing: "ביגוד",
    books: "ספרים",
    orCreateNewCategory: "או צור קטגוריה חדשה",
    newCategoryName: "שם קטגוריה חדשה",
    addCategory: "הוסף",
    category: "קטגוריה",
    categories: "קטגוריות",
    myItems: "הפריטים שלי",
    messages: "הודעות",
    profile: "פרופיל",
    search: "חפש פריטים...",
    viewAll: 'הצג הכל',
    admin: 'מנהל',
    login: 'התחבר',
    logout: 'התנתק',
    browseItems: 'עיון בפריטים',
    browseServices: 'עיון בשירותים',
    signIn: 'התחבר',
    register: 'הירשם',
    editProfile: 'ערוך פרופיל',
    heroTitle: "מסחר חכם לאנשים חכמים",
    cars: 'מכוניות',
    motorcycles: 'אופנועים',
    boats: 'סירות',
    realEstate: 'נדל"ן',
    phones: 'טלפונים',
    computers: 'מחשבים',
    gaming: 'גיימינג',
    cameras: 'מצלמות',
    watches: 'שעונים',
    jewelry: 'תכשיטים',
    handbags: 'תיקים',
    sneakers: 'נעלי ספורט',
    fashion: 'אופנה',
    furniture: 'ריהוט',
    art: 'אמנות',
    pets: 'חיות מחמד',
    services: 'שירותים',
    other: 'אחר',
    condition: 'מצב',
    location: 'מיקום',
    lookingFor: 'מחפש/ת',
    cashFlexibility: 'גמישות במזומן',
    estimated: 'שווי מוערך',
    makeOffer: 'הצע הצעה',
    yourOffer: 'ההצעה שלך',
    theirItem: 'הפריט שלהם',
    addCash: 'הוסף מזומן',
    requestCash: 'בקש מזומן',
    sendOffer: 'שלח הצעה',
    balance: 'איזון',
    tradeOfferDescription: 'בחר פריט להציע, או צור חדש, ו/או הוסף מזומן.',
    createNewItemOffer: 'צור הצעת פריט חדש',
    image: 'תמונה',
    title: 'כותרת',
    description: 'תיאור',
    estimatedValue: 'שווי מוערך',
    new: 'חדש',
    likeNew: 'כמו חדש',
    excellent: 'מצוין',
    good: 'טוב',
    fair: 'סביר',
    willingToAdd: 'מוכן להוסיף מזומן',
    willingToReceive: 'מוכן לקבל מזומן',
    both: 'שניהם',
    tradeOnly: 'החלפה בלבד',
    Anything: 'הכל',
    'Like_new': 'כמו חדש',
    'like_new': 'כמו חדש',
    'willing_to_add': 'מוכן להוסיף מזומן',
    'willing_to_receive': 'מוכן לקבל מזומן',
    'trade_only': 'החלפה בלבד',
    featuredItems: 'פריטים נבחרים',
    howItWorks: {
      title: 'איך סוואפ-אקס עובד',
      step1: {
        title: '1. הציגו את הפריט שלכם',
        description: "צלמו כמה תמונות, כתבו תיאור מושך וקבעו שווי מוערך לפריט שלכם. גרמו לו לבלוט!",
      },
      step2: {
        title: '2. גלו אוצרות',
        description: 'דפדפו בעולם של פריטים ממשתמשים אחרים. השתמשו בחיפוש שלנו כדי למצוא בדיוק את מה שאתם מחפשים. המציאה הבאה שלכם מחכה.',
      },
      step3: {
        title: '3. סגרו עסקה',
        description: 'הציעו החלפה על ידי הצעת הפריטים שלכם. תוכלו להוסיף או לבקש מזומן כדי לאזן את העסקה. נהלו משא ומתן, הסכימו והתכוננו להחלפה!',
      },
    },
    active: 'פעיל',
    pending: 'ממתין',
    requestCashFromThem: 'בקש מהם מזומן',
    message: 'הודעה',
    newOfferTitlePlaceholder: "הכנס כותרת תמציתית לפריט שלך (לדוגמה, 'שעון וינטג', 'מחשב גיימינג')",
    newOfferDescriptionPlaceholder: "ספק תיאור מפורט של הפריט שלך, כולל מצב, תכונות וכל פגמים.",
    estimatedValueHelp: "הכנס את השווי המוערך של הפריט שלך בדולר. זה עוזר לאזן את העסקה.",
    imageHelp: "העלה תמונה ברורה של הפריט שלך. קובץ אחד מקסימום. (פורמטים נתמכים: JPG, PNG)",
    addCashHelp: "השתמש בסליידר כדי להוסיף מזומן להצעה שלך. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
    requestCashHelp: "השתמש בסליידר כדי לבקש מזומן מהצד השני. הערך המקסימלי יתבסס על השווי המוערך של פריט היעד.",
    sendMessagePlaceholder: "כתוב הודעה ידידותית לצד השני, הסבר את הצעתך.",
    tradeOfferSentSuccessfully: "הצעת החלפה נשלחה בהצלחה!",
    failedToSendOffer: "שליחת הצעת החלפה נכשלה.",
    preview: "תצוגה מקדימה",
    lookingForHelp: "בחר קטגוריות של פריטים שאתה מחפש לקבל בהחלפה. באפשרותך לבחור מספר קטגוריות.",
    cashFlexibilityHelp: "הגדר את העדפות המזומן שלך. 'מוכן להוסיף מזומן' פירושו שאתה יכול להציע מזומן. 'מוכן לקבל מזומן' פירושו שאתה יכול לבקש מזומן. 'שניהם' מאפשר את שניהם. 'החלפה בלבד' פירושו ללא מזומן.",
    titleRequired: "נדרשת כותרת.",
    categoryRequired: "נדרשת קטגוריה.",
    valueRequired: "נדרש שווי מוערך.",
    minimumValue: "הערך המינימלי הוא 1.",
    quickLinks: "קישורים מהירים",
    company: "חברה",
    aboutUs: "אודותינו",
    careers: "קריירה",
    press: "עיתונות",
    legal: "משפטי",
    termsOfService: "תנאי שימוש",
    privacyPolicy: "מדיניות פרטיות",
    myCoins: "המטבעות שלי",
    yourCoins: "המטבעות שלך",
    dailyRewardInfo: "אתה מקבל 5 מטבעות מדי יום בהתחברות.",
    nextReward: "התגמול הבא יהיה זמין ב:",
    coinUsage: "שימוש במטבעות",
    featureItemWithCoins: "אתה יכול להשתמש במטבעות כדי להבליט את הפריטים שלך. פריטים מובלטים מופיעים באופן בולט ומקבלים יותר נראות.",
    featureCost: "הבלטת פריט עולה 5 מטבעות ונמשכת 12 שעות. אתה יכול להבליט את הפריטים שלך מדף 'הפריטים שלי'.",
    availableNow: "זמין כעת",
    locationPlaceholder: "לדוגמה, תל אביב",
    emailAddress: "כתובת אימייל",
    emailRequired: "נדרשת כתובת אימייל.",
    password: "סיסמה",
    passwordRequired: "נדרשת סיסמה.",
    signingIn: "מתחבר...",
    noAccount: "אין לך חשבון? הירשם",
    registerAccount: "רשום את חשבונך",
    fullName: "שם מלא",
    fullNamePlaceholder: "שם מלא",
    fullNameRequired: "נדרש שם מלא.",
    emailAddressPlaceholder: "כתובת אימייל",
    passwordPlaceholder: "סיסמה",
    passwordMinLength: "הסיסמה חייבת להיות באורך של 6 תווים לפחות",
    confirmPassword: "אישור סיסמה",
    confirmPasswordPlaceholder: "אישור סיסמה",
    confirmPasswordRequired: "נדרש אישור סיסמה.",
    passwordsMismatch: "הסיסמאות אינן תואמות",
    registering: "רושם...",
    alreadyHaveAccount: "כבר יש לך חשבון? התחבר",
    items: "פריטים",
    selectCategory: "בחר קטגוריה",
    loading: "טוען...",
    mainImageRequired: "תמונה ראשית (חובה)",
    uploadAFile: "העלה קובץ",
    orDragAndDrop: "או גרור ושחרר",
    imageFormats: "PNG, JPG, GIF עד 10MB",
    uploadFiles: "העלה קבצים",
    additionalImagesOptional: "תמונות נוספות (אופציונלי)",
    conditionRequired: "מצב הפריט נדרש",
    selectCondition: "בחר מצב",
    selectLookingFor: "בחר פריטים שאתה מחפש",
    lookingForOptional: "מחפש (אופציונלי)",
    listMyItem: "פרסם את הפריט שלי",
    itemsFoundSuffix: "פריטים נמצאו",
    errorLoadingItems: "שגיאה בטעינת פריטים",
    filterBy: "סינון לפי",
    priceRange: "טווח מחירים",
    applyFilters: "החל סינון",
    clearFilters: "נקה סינון",
    minPrice: "מחיר מינימום",
    maxPrice: "מחיר מקסימום",
    gridView: "תצוגת רשת",
    listView: "תצוגת רשימה",
    categoryCreated: "הקטגוריה נוצרה בהצלחה!",
    categoryNameEmpty: "שם הקטגוריה לא יכול להיות ריק",
    itemListedSuccess: "הפריט פורסם בהצלחה!",
    mainImageRequiredError: "אנא העלה תמונה ראשית לפריט שלך.",
    holdCtrl: "החזק Ctrl/Cmd כדי לבחור מרובים",
    selectItemsToOffer: "בחר פריטים להצעה",
    noItemsToList: "עדיין לא פרסמת פריטים.",
    cashAdjustment: "התאמת מזומן",
    iWillAddCash: "אני אוסיף מזומן",
    iRequestCash: "אני מבקש מזומן",
    sendOffer: "שלח הצעה",
    offerSent: "ההצעה נשלחה בהצלחה!",
    startConversation: "התחל את השיחה!",
    tradeOffer: "הצעת החלפה",
    sendImage: "שלח תמונה",
    typeAMessage: "כתוב הודעה...",
    sendContactInfo: "שלח פרטי קשר",
    messageSentSuccessfully: "ההודעה נשלחה בהצלחה",
    failedToSendChatMessage: "שליחת ההודעה נכשלה",
    failedToUploadMedia: "העלאת המדיה נכשלה",
    errorLoadingMessages: "שגיאה בטעינת הודעות",
    noMessagesFound: "לא נמצאו הודעות",
    yourItems: "הפריטים שלך",
    iAddCash: "אני מוסיף מזומן 💸",
    iRequestCash: "אני מבקש מזומן 🤲",
    none: "ללא",
    clear: "נקה",
    offering: "מציע",
    customOffer: "הצעה מותאמת אישית",
    cancelCustomItem: "בטל פריט מותאם",
    orCreateCustomOffer: "או צור הצעה מותאמת אישית",
    tradingFor: "מחליף עבור",
    noItemsListed: "אין לך פריטים רשומים עדיין.",
    basicInfo: "מידע בסיסי",
    itemDetails: "פרטי הפריט",
    media: "מדיה",
    tradingPreferences: "העדפות מסחר",
    createItemSubtitle: "הפוך את הפריטים שאינך בשימוש למשהו חדש. מלא את הפרטים למטה.",
    noItemsSelected: "לא נבחרו פריטים",
    searchCategories: "חפש קטגוריות...",
    searchServices: "חפש שירותים...",
    filters: "סינון",
    item: "פריט",
    service: "שירות",
    hourlyRate: "מחיר לשעה",
    loginToTrade: "אנא התחבר כדי להגיש הצעת החלפה.",
    claimReward: "קבל בונוס יומי",
    contactSupport: "צור קשר עם תמיכה",
    browseItemsSubtitle: "גלה פריטים ייחודיים להחלפה",
    browseServicesSubtitle: "מצא אנשי מקצוע לצרכים שלך",
    upTo: "עד",
    clearAll: "נקה הכל",
    noItemsFoundMatching: "לא נמצאו פריטים המתאימים לקריטריונים שלך.",
    noServicesFound: "לא נמצאו שירותים.",
    perHour: "/שעה",
    flexible: "גמיש",
    notSpecified: "לא צוין",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'he');
  const [dir, setDir] = useState('rtl');

  useEffect(() => {
    localStorage.setItem('language', language);
    const rtlLanguages = ['he'];
    setDir(rtlLanguages.includes(language) ? 'rtl' : 'ltr');
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key, defaultValue) => {
    if (!key || typeof key !== 'string') return defaultValue || key;
    const resolve = (path, obj) => path.split('.').reduce((prev, curr) => prev ? prev[curr] : null, obj) 
    const translation = resolve(key, translations[language]) || resolve(key, translations.en);
    return translation || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' },
];
